Repository calf-nursery/test-infra, pull requests merged in 2023-09, with the labels that each got.

#50 Attempt to fix configmap update propagation
  jobs/rancher-turtles/rancher-turtles_presubmits.yaml
  jobs/test-infra/branch_protector/branch_protector_periodics.yaml
  jobs/test-infra/label_sync/label_sync_periodics.yaml
  jobs/test-infra/peribolos/peribolos_postsubmit.yaml
  jobs/testapp/testapp_presubmits.yaml
Labels: lgtm, approved, release-note-none

#51 feat: Enable plugins in all repos and extend the document
  README.md
  config/prow/plugins.yaml
  jobs/rancher-turtles/rancher-turtles-presubmits-main.yaml
  jobs/rancher-turtles/rancher-turtles-presubmits-release-0-1.yaml
  jobs/testapp/testapp-presubmits-main.yaml
  jobs/testapp/testapp-presubmits-release-0-1.yaml
Labels: kind/feature, lgtm, approved, release-note, kind/documentation

#53 Set 'allow_merge_commit' to true in repos
  config/prow/org.yaml
Labels: lgtm, approved, release-note

#55 Attempt to fix cherry pick plugin
  config/prow/plugins.yaml
Labels: release-note

#59 Allow squash merge
  config/prow/org.yaml
Labels: kind/bug, lgtm, approved, release-note-none

#61 Enable milestone_applier in repos
  config/prow/plugins.yaml
Labels: kind/feature, lgtm, approved, release-note-none
