Repository calf-nursery/test-infra, pull requests merged in 2023-08, with the labels that each got.

#2 Fix indentation in OWNERS
  OWNERS
Labels: lgtm

#1 chore: updated plugins/config to match cluster
  config.yaml
  plugins.yaml
Labels: lgtm, approved

#4 chore: added needs-rebase external plugin
  config/prow/plugins.yaml
Labels: lgtm, approved

#5 chore: updated sample jobs
  jobs/sample.yaml
  jobs/testapp/presubmits.yaml
Labels: lgtm, approved

#6 chore: various config changes
  config/prow/config.yaml
  config/prow/plugins.yaml
Labels: lgtm, approved

#7 chore: various config changes
  config/prow/config.yaml
  jobs/testapp/presubmits.yaml
Labels: lgtm, approved

#8 chore: added job-config flags
  config/prow/base/crier.yaml
  config/prow/base/deck.yaml
  config/prow/base/hook.yaml
  config/prow/base/horologium.yaml
  config/prow/base/prow-controller-manager.yaml
  config/prow/base/sinker.yaml
  config/prow/base/statusreconciler.yaml
  config/prow/base/tide.yaml
  jobs/sample.yaml
Labels: lgtm, approved

#9 chore: updated testapp build job
  jobs/testapp/presubmits.yaml
Labels: lgtm, approved

#10 chore: more testing of jobs
  jobs/testapp/presubmits.yaml
Labels: lgtm, approved

#11 chore: added verification job
  jobs/testapp/presubmits.yaml
Labels: lgtm, approved

#12 chore: added sinker config
  config/prow/config.yaml
Labels: lgtm, approved

#13 chore: commented out the resource requests
  jobs/testapp/presubmits.yaml
Labels: lgtm, approved

#14 chore: adding peribolos
  config/prow/base/ingress.yaml
  config/prow/base/kustomization.yaml
  config/prow/base/pdb.yaml
  config/prow/kustomization.yaml
  config/prow/org.yaml
  jobs/test-infra/peribolos/presubmit.yaml
Labels: lgtm, approved

#15 Prow: Add external plugins and enable various prow configurations
  README.md
  config/prow/external-plugins/cherrypicker_deployment.yaml
  config/prow/external-plugins/cherrypicker_service.yaml
  config/prow/kustomization.yaml
  config/prow/labels.yaml
  config/prow/plugins.yaml
  jobs/testapp/presubmits.yaml
Labels: lgtm, approved

#17 Add rancher turtles jobs
  jobs/rancher-turtles/presubmits.yaml
Labels: lgtm, approved

#18 Enable release-note plugin
  README.md
  config/prow/plugins.yaml
Labels: lgtm, approved

#20 Fix typos in org names
  README.md
  config/prow/plugins.yaml
Labels: lgtm, approved, release-note

#21 Add needs rebase external plugin manifests
  config/prow/external-plugins/needs-rebase_deployment.yaml
  config/prow/external-plugins/needs-rebase_service.yaml
  config/prow/kustomization.yaml
Labels: lgtm, approved, release-note

#22 fix: various changes for external plugins
  config/prow/external-plugins/cherrypicker_deployment.yaml
  config/prow/external-plugins/needs-rebase_deployment.yaml
  config/prow/plugins.yaml
Labels: lgtm, approved, release-note-none

#26 chore: added override plugin
  config/prow/plugins.yaml
Labels: lgtm, approved, release-note-none

#27 Remove duplicate needs rebase
  config/prow/plugins.yaml
Labels: lgtm, approved, release-note-none

#28 chore: updated external plugins
  config/prow/plugins.yaml
Labels: lgtm, approved, do-not-merge/release-note-label-needed

#25 chore: changed perobolos to post submit and confirm
  jobs/test-infra/peribolos/postsubmit.yaml
Labels: lgtm, approved, release-note-none

#23 test: small change to test peribolos job
  config/prow/org.yaml
Labels: lgtm, approved, release-note-none

#29 Add issue/pr templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved, release-note

#30 Update README.md
  README.md
Labels: lgtm, approved, release-note-none

#31 Update org.yaml
  config/prow/org.yaml
Labels: lgtm, approved, release-note-none

#32 Update postsubmit.yaml
  jobs/test-infra/peribolos/postsubmit.yaml
Labels: lgtm, approved, release-note-none

#33 Update org.yaml
  config/prow/org.yaml
Labels: lgtm, approved, release-note-none

#34 Update org.yaml
  config/prow/org.yaml
Labels: lgtm, approved, release-note-none

#35 Update org.yaml
  config/prow/org.yaml
Labels: lgtm, approved, release-note-none

#37 Add and e2e test presubmit job
  config/prow/config.yaml
  jobs/rancher-turtles/presubmits.yaml
Labels: release-note

#38 Update config.yaml with merge_method
  config/prow/config.yaml
Labels: lgtm, approved, release-note

#39 Update presubmits.yaml for turtles - amend resource requests for now
  jobs/rancher-turtles/presubmits.yaml
Labels: lgtm, approved, release-note-none

#42 chore: minor change to jobs and increase history to 24h
  config/prow/config.yaml
  jobs/test-infra/branch_protector/periodics.yaml
  jobs/test-infra/label_sync/periodics.yaml
Labels: lgtm, approved, release-note-none

#43 Add gcs variable to link into job artifacts
  config/prow/config.yaml
Labels: lgtm, approved, release-note

#47 Enable lifecycle and retitle plugins
  config/prow/plugins.yaml
Labels: kind/feature, lgtm, approved, release-note

#46 Add autobump periodic
  config/prow/autobump-config/prow-job-autobump-config.yaml
  config/prow/kustomization.yaml
  config/prow/plugins.yaml
  jobs/test-infra/label_sync/periodics.yaml
Labels: lgtm, approved, release-note

#49 Update k8s-staging-test-infra images as needed
  jobs/rancher-turtles/presubmits.yaml
  jobs/testapp/presubmits.yaml
Labels: lgtm, approved, release-note-none

#48 Add gcsweb deployment and use it in config
  config/prow/base/gcsweb.yaml
  config/prow/base/ingress.yaml
  config/prow/base/kustomization.yaml
  config/prow/config.yaml
Labels: lgtm, approved, release-note, kind/cleanup
